global: configurable field names
inveniosoftware/invenio-orcid pull request #7
Opened 2016-07-28 12:27 UTC by Panos512

* All the installation-based field names are now configurable.
  (addresses #4)

Signed-off-by: Panos Paparrigopoulos <panos.paparrigopoulos@cern.ch>

2016-07-28 12:35 UTC, jirikuncar commented on invenio_orcid/config.py
> +AUTHORS_ELASTICSEARCH_INDEX_NAME = 'records-authors'
Please follow naming convention using `ORCID_` prefix.

2016-07-28 13:08 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_MAIN_RECORDS_IDENTIFIER = 'control_number'
It would be better to use persistent identifier fetcher (`recid`).

2016-07-28 13:09 UTC, jirikuncar commented on invenio_orcid/tasks.py
> +                    print(e.response.text, sender[record_identifier])
please don't use `print`

2016-07-28 13:09 UTC, jirikuncar commented on invenio_orcid/tasks.py
>                      logger.info("Failed to push " +
`current_app.logger.info`

2016-07-28 13:13 UTC, jirikuncar commented on invenio_orcid/tasks.py
> +                                sender.get(record_identifier) + " to orcid.")
It's better to use string formatting then concatenation.

```
'Failed to push {0} to ORCID.'.format(sender.get(record_identifier))
```

2016-07-28 15:29 UTC, Panos512 commented on invenio_orcid/config.py
> +ORCID_MAIN_RECORDS_IDENTIFIER = 'control_number'
I am afraid I don't fully understand.

You mean this one:

https://github.com/inveniosoftware/invenio-pidstore/blob/master/invenio_pidstore/fetchers.py#L54

but this takes the `uuid` as an argument and in our case that's what we are trying to get using the `recid` which in inspire's case is called `control_number`

https://github.com/Panos512/invenio-orcid/blob/7904c68c2fdadadcc247e288160e76065a872c99/invenio_orcid/tasks.py#L51


If I understood correctly we need a fetcher that extracts the `recid` from a given record.

2016-07-28 15:42 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_MAIN_RECORDS_IDENTIFIER = 'control_number'
You can simplify the code in tasks.py by using fetcher:

```
pid = current_pidstore.fetchers[fetcher_name](None, json)
```

2016-07-29 15:03 UTC, jirikuncar commented
ping @Panos512

2016-08-02 07:45 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_AUTHORS_ELASTICSEARCH_INDEX_NAME = 'records-authors'
Can you use search classes?

- https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/api.py#L49
- https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/config.py#L44

```
ORCID_AUTHORS_SEARCH_CLASS = ...
ORCID_RECORDS_SEARCH_CLASS = ...
```

2016-08-05 13:26 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_AUTHORS_SEARCH_CLASS = "current_app.config[RECORDS_REST_ENDPOINTS]" \
You can do it as default when set to `None`, but not in this way. Preferably, just specify the importable string directly here.

2016-08-05 13:27 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_MAIN_RECORDS_PID_TYPE_NAME = 'literature'
`ORCID_RECORDS_PID_TYPE`

2016-08-05 13:27 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_MAIN_RECORDS_DOC_TYPE = 'hep'
`ORCID_RECORDS_DOC_TYPE`

2016-08-05 13:28 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_MAIN_PIDSTORE_FETCHER = 'my_recid_fetcher'
`ORCID_PID_FETCHER`

2016-08-05 13:30 UTC, jirikuncar commented on invenio_orcid/tasks.py
> +    AuthorSearch = import_string(
It's good idea to move it to the state object of InvenioORCID extension.

--
Check the pattern in https://github.com/inveniosoftware/invenio-access/blob/master/invenio_access/ext.py

2016-08-09 13:14 UTC, kaplun commented on invenio_orcid/config.py
> +ORCID_RECORDS_DOC_TYPE = 'hep'
I think we can put literature here as well, since `hep` it's really INSPIRE specific.

2016-09-20 15:10 UTC, jirikuncar commented on invenio_orcid/ext.py
> +            or None
not necessary, `get` returns `None` if the key does not exist.

2016-09-20 15:11 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_AUTHORS_SEARCH_CLASS = "invenio_search:RecordsSearch"
please use single quotes consistently

2016-09-20 15:12 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_RECORDS_PID_TYPE = 'literature'
default should be probably `records` for non-inspire use-cases

2016-09-20 15:12 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_RECORDS_PID_FETCHER = 'my_recid_fetcher'
`recid_fetcher`

2016-09-20 15:16 UTC, jirikuncar commented on invenio_orcid/tasks.py
> +    AuthorSearch = current_orcid.author_search
`return current_orcid.author_search.execute(es_query).hits.hits`

2016-09-20 15:16 UTC, jirikuncar requested changes

2016-09-20 19:48 UTC, kaplun commented on invenio_orcid/config.py
> +ORCID_RECORDS_PID_TYPE = 'literature'
Actually would it be possible to make this a list? Already in INSPIRE we are going to push to ORCID `literature` and `data`.

2016-09-20 19:49 UTC, kaplun commented on invenio_orcid/config.py
>  ORCID_WORK_TYPES = {
This list is valid only in INSPIRE. Should probably be commented out and the default being empty dict.

2016-09-20 19:58 UTC, jirikuncar commented on invenio_orcid/config.py
> +ORCID_RECORDS_PID_TYPE = 'literature'
Can it be solved with only `ORCID_RECORDS_PID_FETCHER` that can fetch both types and `ORCID_RECORD_SEARCH_CLASS`?

2016-09-23 08:30 UTC, jirikuncar commented on invenio_orcid/ext.py
> +        author_search = self.app.config.get('ORCID_AUTHORS_SEARCH_CLASS') \
extra `\` at the end of line

2016-09-23 08:31 UTC, jirikuncar commented on invenio_orcid/tasks.py
> +        current_app.logger.info("Sending {0} to orcid.").format(
`'Sending "{0}" to orcid.'`

2016-09-23 08:31 UTC, jirikuncar requested changes

2016-09-26 08:39 UTC, jirikuncar commented on invenio_orcid/config.py
> +# Mapping to orcid work_types
You can convert this comment to a docstring.

```python
ORCID_WORK_TYPES = {}
"""Mapping to ORCID work types.

Example:

.. code-block:: python

    ORCID_WORK_TYPES = {
        'conferencepaper': 'CONFERENCE_PAPER',
        'proceedings': 'BOOK',
    }
```

2016-09-26 08:40 UTC, jirikuncar commented on invenio_orcid/tasks.py
> +                        "Succersfully sent {0} to orcid.").format(
Try to use consistent style with line 117.

2016-09-26 08:40 UTC, jirikuncar commented on invenio_orcid/tasks.py
> +                        "Failed to push {0} to orcid.").format(
see https://github.com/inveniosoftware/invenio-orcid/pull/7/files#r80429308

2016-09-26 08:40 UTC, jirikuncar commented on invenio_orcid/tasks.py
> +                "Failed to convert {0} to orcid.").format(
see https://github.com/inveniosoftware/invenio-orcid/pull/7/files#r80429308

2016-09-26 12:22 UTC, Panos512 commented on invenio_orcid/tasks.py
> +                        "Succersfully sent {0} to orcid.").format(
Pep8 complains for long lines if I use the same style as line 117.
Should I change 117 to follow the others?

2016-09-26 13:03 UTC, jirikuncar commented on invenio_orcid/tasks.py
> +                        "Succersfully sent {0} to orcid.").format(
@Panos512 my comment was about using consistently single quotes and string formatting. For everything else just follow PEP8, file context and common sense with the aim of maximum code readability.

2016-09-28 07:33 UTC, jirikuncar approved these changes

2016-09-28 07:35 UTC, jirikuncar commented
@Panos512 This branch is out-of-date with the base branch.

2016-09-28 09:03 UTC, Panos512 commented
@jirikuncar it's rebased now.

2016-09-28 09:24 UTC, merged